# Generated by Django 3.1.2 on 2020-10-30 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoBD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanzamientos',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='reviews',
            name='imagen',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
