# Generated by Django 3.1.2 on 2020-10-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoBD', '0004_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tags',
            name='sigla',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='tags',
            name='sigla2',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
