# Generated by Django 3.1.2 on 2020-10-31 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoBD', '0005_auto_20201030_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='link',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='link',
        ),
    ]
