# Generated by Django 3.1.2 on 2020-11-02 00:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoBD', '0009_auto_20201101_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecnac',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
