# Generated by Django 3.1.2 on 2020-11-03 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoBD', '0010_auto_20201101_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='lanzamientos',
            name='nintendo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lanzamientos',
            name='pc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lanzamientos',
            name='playstation',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lanzamientos',
            name='retro',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lanzamientos',
            name='xbox',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='nintendo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='pc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='playstation',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='retro',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noticia',
            name='xbox',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
