# Generated by Django 3.1.2 on 2020-11-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajoBD', '0012_auto_20201103_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='nintendo',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='pc',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='playstation',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='retro',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='xbox',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
